import { Router } from 'express';
import nodemailer from 'nodemailer';

const router = Router();

// ── Create reusable transporter ──
// Uses Gmail SMTP if credentials are set, otherwise falls back to Ethereal test
let transporterPromise;

async function getTransporter() {
  if (transporterPromise) return transporterPromise;

  transporterPromise = (async () => {
    // Check for Gmail credentials
    if (process.env.GMAIL_USER && process.env.GMAIL_APP_PASSWORD) {
      console.log('[Email] Using Gmail SMTP transport');
      return nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: process.env.GMAIL_USER,
          pass: process.env.GMAIL_APP_PASSWORD,
        },
      });
    }

    // Fallback: use Ethereal test account
    console.log('[Email] No Gmail credentials found. Creating Ethereal test account...');
    const testAccount = await nodemailer.createTestAccount();
    console.log(`[Email] Ethereal test account: ${testAccount.user}`);
    return nodemailer.createTransport({
      host: 'smtp.ethereal.email',
      port: 587,
      secure: false,
      auth: {
        user: testAccount.user,
        pass: testAccount.pass,
      },
    });
  })();

  return transporterPromise;
}

function buildHtmlBody(subject, severity, zone, label, confidence, reasoning) {
  const color = severity === 'critical' ? '#ef4444' : severity === 'warning' ? '#f97316' : '#eab308';
  return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>${subject}</title></head>
<body style="font-family: 'Segoe UI', Arial, sans-serif; background: #0f172a; color: #e2e8f0; padding: 24px; margin: 0;">
  <div style="max-width: 600px; margin: 0 auto; background: #1e293b; border-radius: 12px; overflow: hidden; border: 1px solid #334155;">
    <div style="background: ${color}; padding: 20px 24px;">
      <h1 style="margin: 0; color: white; font-size: 20px;">🌊 AquaSentinel Alert</h1>
      <p style="margin: 8px 0 0; color: rgba(255,255,255,0.9); font-size: 14px;">${subject}</p>
    </div>
    <div style="padding: 24px;">
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 16px;">
        <tr>
          <td style="padding: 8px 0; color: #94a3b8; font-size: 12px; text-transform: uppercase;">Zone</td>
          <td style="padding: 8px 0; color: #e2e8f0; font-weight: 600;">${zone}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #94a3b8; font-size: 12px; text-transform: uppercase;">Type</td>
          <td style="padding: 8px 0; color: #e2e8f0;">${label || 'Unknown'}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #94a3b8; font-size: 12px; text-transform: uppercase;">Severity</td>
          <td style="padding: 8px 0;"><span style="background: ${color}; color: white; padding: 2px 10px; border-radius: 99px; font-size: 11px; font-weight: 700;">${severity?.toUpperCase()}</span></td>
        </tr>
        <tr>
          <td style="padding: 8px 0; color: #94a3b8; font-size: 12px; text-transform: uppercase;">Confidence</td>
          <td style="padding: 8px 0; color: #e2e8f0; font-family: monospace;">${confidence}%</td>
        </tr>
      </table>
      <div style="background: #0f172a; border-radius: 8px; padding: 16px; margin-bottom: 16px;">
        <p style="margin: 0 0 4px; font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em;">AI Analysis</p>
        <p style="margin: 0; line-height: 1.7; font-size: 13px; color: #cbd5e1;">${reasoning || 'Anomaly detected by monitoring system.'}</p>
      </div>
      <p style="margin: 0; font-size: 11px; color: #475569; text-align: center;">
        Generated by AquaSentinel Multi-Agent Pipeline • ${new Date().toISOString()}
      </p>
    </div>
  </div>
</body>
</html>`.trim();
}

// ─── POST /api/email/dispatch — Send an approved alert email ───────────
router.post('/dispatch', async (req, res, next) => {
  try {
    const { recipient, subject, severity, zone_name, label, confidence, reasoning } = req.body;

    if (!recipient || !subject) {
      return res.status(400).json({ error: 'recipient and subject are required' });
    }

    const html = buildHtmlBody(subject, severity, zone_name, label, confidence, reasoning);
    const transporter = await getTransporter();

    const fromAddress = process.env.GMAIL_USER || 'aquasentinel@noreply.com';

    const info = await transporter.sendMail({
      from: `"AquaSentinel Alerts" <${fromAddress}>`,
      to: recipient,
      subject: subject,
      html: html,
    });

    // If using Ethereal, get the preview URL
    const previewUrl = nodemailer.getTestMessageUrl(info);

    console.log(`[Email] Sent to ${recipient} — Message ID: ${info.messageId}`);
    if (previewUrl) console.log(`[Email] Preview URL: ${previewUrl}`);

    res.json({
      sent: true,
      messageId: info.messageId,
      previewUrl: previewUrl || null,
    });
  } catch (err) {
    console.error('[Email] Send failed:', err.message);
    res.status(500).json({ error: 'Email send failed', detail: err.message });
  }
});

// ─── GET /api/email/test — Quick test to verify SMTP ─────────────────
router.get('/test', async (_req, res, next) => {
  try {
    const transporter = await getTransporter();
    await transporter.verify();
    res.json({ smtp_ok: true, message: 'SMTP connection verified' });
  } catch (err) {
    res.status(500).json({ smtp_ok: false, error: err.message });
  }
});

export default router;
